### ISSUE TITLE
Add automated testing

### ISSUE THREAD

**Issue by bwinkers** [Ultri-Izzup/ultri-platform#5]
Use [vitest](https://vitest.dev/guide/why.html) because Cypress is unwieldy, Jest isn't compatible with Vite out of the box, and vitest was designed to feel very similar to Jest anyway. Consult these [quasar docs](https://testing.quasar.dev/packages/unit-vitest/) to install it. Use [Postman collection](https://github.com/Ultri-Izzup/ultri-infrastructure/blob/fixes/postman/A-Simple-test.postman_collection.json) for reference and inspiration.

**Comment by npetrangelo** [comment]
Opting to put the API tests in the API subproject, which doesn't actually use Vite and Jest is simple to set up so I'm using Jest instead
